### ISSUE TITLE
The octomapfg method yields the wrong results.

### ISSUE THREAD

**Issue by rickkcir** [KTH-RPL/DynamicMap_Benchmark#9]
Hi, it's a nice work, I like it.

When I run your open source code(octomapfg method), I get the following result, the point cloud is all white, I don't get the same result as removert, what is the reason?

Wrong result
![screenshot_1](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/67400101/9423b810-12af-49a3-9d27-bf008660dfdf)

Correct result
![screenshot](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/67400101/f0ad5d47-57fc-4e43-9476-93440b1423e0)

**Comment by Kin-Zhang** [comment]
It's correct, since I didn't save intensity for octomapfg, click here to get a better view:
![image](https://github.com/KTH-RPL/DynamicMap_Benchmark/assets/35365764/21664eff-dc9c-4261-80ac-b28d0987757b)

All methods output a clean map, some method still save original intensity information, some not. If you want to eval pls, check: https://github.com/KTH-RPL/DynamicMap_Benchmark/blob/master/scripts/cpp/export_eval_pcd.cpp
